/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package au.com.billingbuddy.porlet.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BusinessType service. Represents a row in the &quot;BusinessType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link au.com.billingbuddy.porlet.services.model.impl.BusinessTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link au.com.billingbuddy.porlet.services.model.impl.BusinessTypeImpl}.
 * </p>
 *
 * @author Edicson Morales
 * @see BusinessType
 * @see au.com.billingbuddy.porlet.services.model.impl.BusinessTypeImpl
 * @see au.com.billingbuddy.porlet.services.model.impl.BusinessTypeModelImpl
 * @generated
 */
public interface BusinessTypeModel extends BaseModel<BusinessType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a business type model instance should use the {@link BusinessType} interface instead.
	 */

	/**
	 * Returns the primary key of this business type.
	 *
	 * @return the primary key of this business type
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this business type.
	 *
	 * @param primaryKey the primary key of this business type
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the buty_ i d of this business type.
	 *
	 * @return the buty_ i d of this business type
	 */
	public int getButy_ID();

	/**
	 * Sets the buty_ i d of this business type.
	 *
	 * @param Buty_ID the buty_ i d of this business type
	 */
	public void setButy_ID(int Buty_ID);

	/**
	 * Returns the buty_ description of this business type.
	 *
	 * @return the buty_ description of this business type
	 */
	@AutoEscape
	public String getButy_Description();

	/**
	 * Sets the buty_ description of this business type.
	 *
	 * @param Buty_Description the buty_ description of this business type
	 */
	public void setButy_Description(String Buty_Description);

	/**
	 * Returns the buty_ status of this business type.
	 *
	 * @return the buty_ status of this business type
	 */
	@AutoEscape
	public String getButy_Status();

	/**
	 * Sets the buty_ status of this business type.
	 *
	 * @param Buty_Status the buty_ status of this business type
	 */
	public void setButy_Status(String Buty_Status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BusinessType businessType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BusinessType> toCacheModel();

	@Override
	public BusinessType toEscapedModel();

	@Override
	public BusinessType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}