/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package au.com.billingbuddy.porlet.services.model.impl;

import au.com.billingbuddy.porlet.services.model.BusinessType;
import au.com.billingbuddy.porlet.services.service.BusinessTypeLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the BusinessType service. Represents a row in the &quot;BusinessType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusinessTypeImpl}.
 * </p>
 *
 * @author Edicson Morales
 * @see BusinessTypeImpl
 * @see au.com.billingbuddy.porlet.services.model.BusinessType
 * @generated
 */
public abstract class BusinessTypeBaseImpl extends BusinessTypeModelImpl
	implements BusinessType {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a business type model instance should use the {@link BusinessType} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			BusinessTypeLocalServiceUtil.addBusinessType(this);
		}
		else {
			BusinessTypeLocalServiceUtil.updateBusinessType(this);
		}
	}
}